Add 3.0-RC2 schemas
MobilityData/gbfs-json-schema pull request #100
Opened 2023-11-13 09:21 UTC by tdelmas

Include RC2 changes (listed in the commits names)

2023-11-13 18:58 UTC, richfab commented
Thank you @tdelmas for this very helpful contribution! ⚡ 

I would recommend to include https://github.com/MobilityData/gbfs/pull/559 in this PR once the vote has passed (the vote closes in a few hours).

2023-11-14 20:51 UTC, richfab requested changes
Awesome contribution @tdelmas! Thank you very much!

I added a few change requests.

Also, could you please add `"3.0-RC2"` to the file `v3.0-RC/gbfs_versions.json` like for the other schemas? Thank you!

2023-11-14 20:51 UTC, richfab commented on v3.0-RC2/vehicle_status.json
> +                "description": "The last time this vehicle reported its status to the operator's backend in POSIX time (added in v2.1-RC).",
Let's please update the description to [RFC3339 format](https://www.rfc-editor.org/rfc/rfc3339).

Thank you!

```suggestion
                "description": "The last time this vehicle reported its status to the operator's backend in RFC3339 format (added in v2.1-RC).",
```

2023-11-14 20:51 UTC, richfab commented on v3.0-RC2/system_alerts.json
> +                "minimum": 1450155600
Let's please update the type and format to [RFC3339 format](https://www.rfc-editor.org/rfc/rfc3339).

Thank you!

```suggestion
                "type": "string",
                "format": "date-time"
```

2023-11-14 20:51 UTC, richfab commented on v3.0-RC2/geofencing_zones.json
> +              "vehicle_type_id": {
Let's please replace `vehicle_type_id` with `vehicle_type_ids` here as well. Thank you!

```suggestion
              "vehicle_type_ids": {
```

2023-11-14 20:51 UTC, richfab commented on v3.0-RC2/station_information.json
> +                      "type": "string"
Let's please change the type of `vehicle_type_ids` to an array of strings as defined in https://github.com/MobilityData/gbfs/pull/547.

Thank you!

```suggestion
                      "type": "array",
                      "items": {
                        "type": "string"
                      }
```

2023-11-14 20:51 UTC, richfab commented on v3.0-RC2/station_information.json
> +                  "required": ["vehicle_type_id","count"]
Typo

```suggestion
                  "required": ["vehicle_type_ids","count"]
```

2023-11-14 20:51 UTC, richfab commented on v3.0-RC2/station_information.json
> +                      "type": "string"
Let's please change the type of `vehicle_type_ids` to an array of strings as defined in https://github.com/MobilityData/gbfs/pull/547.

Thank you!

```suggestion
                      "type": "array",
                      "items": {
                        "type": "string"
                      }
```

2023-11-14 20:56 UTC, richfab commented on v3.0-RC2/station_information.json
> +                      "description": "The total number of docks at the station, both available and unavailable, that may accept the corresponding vehicle type as defined by its vehicle_type_id.",
Let's please update the description to match the [spec](https://github.com/MobilityData/gbfs/blob/v3.0-RC2/gbfs.md#station_informationjson). Thank you!

```suggestion
                      "description": "A number representing the total number of docks at the station, both available and unavailable, that may accept the vehicle types specified by vehicle_type_ids.",
```

2023-11-14 20:58 UTC, richfab commented on v3.0-RC2/station_information.json
> +                      "description": "A vehicle_type_id, as defined in vehicle_types.json, that may dock at the station.",
Let's please update the description to match the [spec](https://github.com/MobilityData/gbfs/blob/v3.0-RC2/gbfs.md#station_informationjson). Thank you!

```suggestion
                      "description": "An array of strings where each string represents a vehicle_type_id that is able to use a particular type of dock at the station.",
```

2023-11-14 20:59 UTC, richfab commented on v3.0-RC2/station_information.json
> +                      "description": "A vehicle_type_id, as defined in vehicle_types.json, that may park at the virtual station.",
Let's please update the description to match the [spec](https://github.com/MobilityData/gbfs/blob/v3.0-RC2/gbfs.md#station_informationjson). Thank you!

```suggestion
                      "description": "The vehicle_type_ids, as defined in vehicle_types.json, that may park at the virtual station.",
```

2023-11-14 21:03 UTC, richfab commented on v3.0-RC2/station_information.json
> +                "description": "This field's value is an array of objects containing the keys vehicle_type_id and count defined below. These objects are used to model the total docking capacity of a
Let's please update the description to match the [spec](https://github.com/MobilityData/gbfs/blob/v3.0-RC2/gbfs.md#station_informationjson). Thank you!

```suggestion
                "description": "This field's value is an array of objects containing the keys vehicle_type_ids and count defined below. These objects are used to model the total docking capacity of a station, both available and unavailable, for each type of vehicle that may dock at this station.",
```

2023-11-14 21:05 UTC, richfab commented on v3.0-RC2/station_information.json
> +                      "description": "A number representing the total number of vehicles of the corresponding vehicle_type_id type that can park within the virtual station.",
Let's please update the description to match the [spec](https://github.com/MobilityData/gbfs/blob/v3.0-RC2/gbfs.md#station_informationjson). Thank you!

```suggestion
                      "description": "A number representing the total number of vehicles of the specified vehicle_type_ids that can park within the virtual station.",
```

2023-11-14 21:33 UTC, richfab commented on v3.0-RC/gbfs_versions.json
Actually, in this file I meant to add `"3.0-RC2"` to `data.versions` enum, not to `version` enum. 

Can you please add `"3.0-RC2"` to `data.versions` enum and remove it from `version` enum?

Sorry for the confusion. Thank you!

2023-11-15 08:34 UTC, tdelmas commented on v3.0-RC/gbfs_versions.json
Done, in the two missing places

2023-11-15 08:35 UTC, tdelmas commented
@richfab thank you for that very detailed review! Everything should be fix now

2023-11-15 15:41 UTC, richfab requested changes
Hi @tdelmas! Thank you very much for the fast changes ⚡ We can almost merge 🙌 

- The Timestamp needs to be changed to RFC3339 format in a few more descriptions. 
- `vehicle_type_ids` needs to be changed to plural in one more place.

Thanks to you the JSON Schema are up to date very quickly, so thank you! 🙏

2023-11-15 15:41 UTC, richfab commented on v3.0-RC2/gbfs_versions.json
> +      "description": "Last time the data in the feed was updated in POSIX time.",
```suggestion
      "description": "Last time the data in the feed was updated in RFC3339 format.",
```

2023-11-15 15:41 UTC, richfab commented on v3.0-RC2/geofencing_zones.json
> +      "description": "Last time the data in the feed was updated in POSIX time.",
```suggestion
      "description": "Last time the data in the feed was updated in RFC3339 format.",
```

2023-11-15 15:41 UTC, richfab commented on v3.0-RC2/manifest.json
> +      "description": "Last time the data in the feed was updated in POSIX time.",
```suggestion
      "description": "Last time the data in the feed was updated in RFC3339 format.",
```

2023-11-15 15:41 UTC, richfab commented on v3.0-RC2/station_information.json
> +        "Last time the data in the feed was updated in POSIX time.",
```suggestion
        "Last time the data in the feed was updated in RFC3339 format.",
```

2023-11-15 15:41 UTC, richfab commented on v3.0-RC2/station_status.json
> +        "Last time the data in the feed was updated in POSIX time.",
```suggestion
        "Last time the data in the feed was updated in RFC3339 format.",
```

2023-11-15 15:41 UTC, richfab commented on v3.0-RC2/system_alerts.json
> +        "Last time the data in the feed was updated in POSIX time.",
```suggestion
        "Last time the data in the feed was updated in RFC3339 format.",
```

2023-11-15 15:41 UTC, richfab commented on v3.0-RC2/system_information.json
> +        "Last time the data in the feed was updated in POSIX time.",
```suggestion
        "Last time the data in the feed was updated in RFC3339 format.",
```

2023-11-15 15:41 UTC, richfab commented on v3.0-RC2/system_pricing_plans.json
> +        "Last time the data in the feed was updated in POSIX time.",
```suggestion
        "Last time the data in the feed was updated in RFC3339 format.",
```

2023-11-15 15:41 UTC, richfab commented on v3.0-RC2/system_regions.json
> +        "Last time the data in the feed was updated in POSIX time.",
```suggestion
        "Last time the data in the feed was updated in RFC3339 format.",
```

2023-11-15 15:41 UTC, richfab commented on v3.0-RC2/vehicle_status.json
> +        "Last time the data in the feed was updated in POSIX time.",
```suggestion
        "Last time the data in the feed was updated in RFC3339 format.",
```

2023-11-15 15:41 UTC, richfab commented on v3.0-RC2/vehicle_types.json
> +        "Last time the data in the feed was updated in POSIX time.",
```suggestion
        "Last time the data in the feed was updated in RFC3339 format.",
```

2023-11-15 15:41 UTC, richfab commented on v3.0-RC2/station_information.json
> +                  "required": ["vehicle_type_id","count"]
Typo

```suggestion
                  "required": ["vehicle_type_ids","count"]
```

2023-11-15 16:08 UTC, richfab approved these changes
LGTM! 👏 
Merging now 🚀 
Thank you!

2023-11-15 16:09 UTC, merged