Feat/126 rust language bindings
MobilityData/gbfs-json-schema pull request #128
Opened 2024-06-03 15:24 UTC by Alessandro100

Fixes #126 

This PR merges the repo https://github.com/fluctuo/gbfs_types big thanks to @tdelmas 🎉

Whats been done in this PR

- updated readme
- changed naming from v3.0-rc2 to v3.0

What's next
- CICD configuration
- publishing

2024-06-03 15:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MobilityData/gbfs-json-schema?pullRequest=128) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/MobilityData/gbfs-json-schema?pullRequest=128) before we can accept your contribution.<br/>**2** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: tdelmas<br/>:white_check_mark: Alessandro100<br/>:x: renovate[bot]<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MobilityData/gbfs-json-schema?pullRequest=128) it.</sub>

2024-06-03 15:37 UTC, tdelmas approved these changes

2024-06-03 15:47 UTC, richfab requested changes
Thank you Fluctuo for this 🙏 🙏 🙏 I'm sure this library will benefit many people in the community.

Nice work @Alessandro100. I left one comment.

2024-06-03 15:47 UTC, richfab commented on models/rust/src/3.0/files/system_pricing_plans.rs
> +    pub reservation_price_flat_rate: Option<NonNegativeFloat>,
These 2 fields were removed from v3.0 and added to v3.1-RC ([Release Notes](https://github.com/MobilityData/gbfs/releases/tag/v3.1-RC)).

```suggestion
```

2024-06-03 15:47 UTC, richfab commented on models/rust/src/3.0/files/examples/specification/system_pricing_plans-1.json
> +                "reservation_price_per_min": 0.15,
This field was removed from v3.0 and added to v3.1-RC ([Release Notes](https://github.com/MobilityData/gbfs/releases/tag/v3.1-RC)).

```suggestion
```

2024-06-04 14:15 UTC, richfab approved these changes
LGTM from reading through the files.

It would be good that a dev from MobilityData reviews this PR 🙏

2024-06-04 14:37 UTC, davidgamez approved these changes
Great addition to the language bindings! 🥳

2024-06-04 15:35 UTC, merged